import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/card.css";
import "./styles/typography.css";
import "./styles/sidebar.css";
import "./styles/spacing.css";
import "./styles/accordion.css";
import "./styles/button.css";
import "./styles/alert.css";
import "./styles/alertbox.css";
import "./styles/avatar.css";
import "./styles/badge.css";
import "./styles/ComponentPageLayout.css"
import "./styles/intro.css"
import "./styles/border.css"
import "./styles/footer.css"
import "./styles/themeEditorPanel.css"
import { ThemeProvider } from "@/context/ThemeContext";
import "./styles/progresscircle.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>{children}</ThemeProvider></body>
    </html>
  );
}
